name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: 'Create env file'
        run: |
          touch .env
          echo MONGO=${{ secrets.MONGO }} > .env
          cat .env
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm i"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jamestan-bmake2025-b-89"
          entrypoint: "app.js"
          root: ""
          
          
